# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26e46876adee009702e7a962842be7b3d43379be257cd7d9717c3b6b7ffa94d9579ca96334b04be9b8e5fd26bce70bb86f45ca6378b18ec5b234d10b9c11266

test:
  secret_key_base: 03c8a1640f2de4c5e1e8ce8719e324ae3d0bea27574f120431e58477f911615251740f1a940c1c184c3a227ae01825b6170393c6167374830fc5cf0164150a1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
